"use client";

import BrightCard from "../../../components/cosmic/BrightCard";
import CosmicButton from "../../../components/cosmic/CosmicButton";

const goals = [[5,"Casual","5 min/day"],[10,"Regular","10 min/day"],[20,"Serious","20 min/day"],[50,"Intense","30 min/day"]];
export default function DailyGoalSetup({ value, onChange, onContinue }) { return <main className="cosmic-dark cd-intro-screen cd-intro-goal" style={{ display: "grid", placeItems: "center", padding: 22 }}><span className="cd-goal-glow" aria-hidden="true" /><section className="cd-intro-goal-inner" style={{ width: "min(850px,100%)", textAlign: "center" }}><p className="cd-choice-kicker">STEP 2 OF 2</p><h1 style={{ fontSize: "clamp(2.4rem,7vw,4.6rem)", letterSpacing: "-.06em" }}>Set your daily rhythm</h1><p style={{ color: "#c3d1ed" }}>Choose a goal that feels encouraging and sustainable.</p><div className="cd-goal-grid" style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 14, margin: "28px 0" }}>{goals.map(([xp,title,time]) => <BrightCard key={xp} selected={value === xp} onClick={() => onChange(xp)}><span style={{ fontSize: 26 }} aria-hidden="true">✦</span><strong style={{ display: "block", marginTop: 8, fontSize: 19 }}>{title}</strong><small style={{ color: "#c3d1ed" }}>{time}</small><b>{xp} XP</b></BrightCard>)}</div><CosmicButton onClick={onContinue}>Set Goal <span aria-hidden="true">→</span></CosmicButton></section><style jsx global>{`
  .cd-intro-goal{position:relative;min-height:calc(100svh - 64px);overflow:hidden;background:radial-gradient(circle at 50% 15%,rgba(97,78,220,.22),transparent 38%),#07091a!important}.cd-goal-glow{position:absolute;width:min(78vw,840px);aspect-ratio:1;left:50%;top:47%;border-radius:50%;transform:translate(-50%,-50%);background:radial-gradient(circle,rgba(98,214,255,.13),rgba(150,116,255,.08) 35%,transparent 67%);filter:blur(5px);pointer-events:none}.cd-intro-goal-inner{position:relative;z-index:1}.cd-intro-goal h1{margin:10px 0 8px;line-height:.96}.cd-goal-grid>.cosmic-bright-card{position:relative;min-height:170px;display:grid;align-content:center;justify-items:center;gap:3px;overflow:hidden;border:1px solid rgba(205,224,255,.2)!important;border-radius:22px!important;background:linear-gradient(145deg,rgba(255,255,255,.13),rgba(87,99,189,.08))!important;transition:transform .2s cubic-bezier(.16,1,.3,1),box-shadow .2s ease!important}.cd-goal-grid>.cosmic-bright-card:before{content:"";position:absolute;inset:auto -20% -55%;height:70%;border-radius:50%;background:radial-gradient(ellipse,rgba(94,238,210,.19),transparent 68%);pointer-events:none}.cd-goal-grid>.cosmic-bright-card:hover{transform:translateY(-4px);box-shadow:0 22px 42px rgba(67,219,199,.13)!important}.cd-goal-grid b{position:relative;color:#aaf7d4;font-size:12px}.cd-intro-goal .cosmic-button{min-height:48px!important;border-radius:16px!important;font-weight:900!important}@media(max-width:530px){.cd-goal-grid{grid-template-columns:1fr!important}.cd-goal-grid>.cosmic-bright-card{min-height:128px}}
`}</style></main>; }
