"use client";

import BrightCard from "../../../components/cosmic/BrightCard";
import CosmicButton from "../../../components/cosmic/CosmicButton";
import MascotMale from "../../../components/cosmic/MascotMale";
import MascotFemale from "../../../components/cosmic/MascotFemale";

export default function FirstTimeLessonIntro({ guide, onContinue }) { const Mascot = guide === "female" ? MascotFemale : MascotMale; return <main className="cosmic-dark cd-intro-screen cd-first-lesson" style={{ display: "grid", placeItems: "center", padding: 22 }}><span className="cd-first-grid" aria-hidden="true" /><BrightCard style={{ width: "min(650px,100%)", textAlign: "center", padding: "clamp(26px,6vw,52px)" }}><div className="cd-first-mascot"><Mascot compact /></div><p className="cd-choice-kicker">A QUICK TOUR</p><h1 style={{ margin: "8px 0", fontSize: "clamp(2.2rem,6vw,4rem)", letterSpacing: "-.06em" }}>This is your learning path.</h1><p style={{ color: "#c3d1ed", lineHeight: 1.65 }}>Complete ayahs, earn XP, unlock surahs.</p><div className="cd-first-points" style={{ display: "flex", justifyContent: "center", gap: 16, margin: "24px 0", color: "#b9c9ef", fontWeight: 900 }}><span><b>1</b> AYAH</span><span><b>2</b> XP</span><span><b>3</b> SURAH</span></div><CosmicButton onClick={onContinue}>Show me the path <span aria-hidden="true">→</span></CosmicButton></BrightCard><style jsx global>{`
  .cd-first-lesson{position:relative;min-height:calc(100svh - 64px);overflow:hidden;background:radial-gradient(circle at 50% 40%,rgba(108,82,225,.25),transparent 35%),#07091a!important}.cd-first-grid{position:absolute;inset:0;opacity:.34;background:linear-gradient(rgba(136,183,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(136,183,255,.045) 1px,transparent 1px);background-size:42px 42px;mask-image:radial-gradient(circle at 50% 45%,black,transparent 68%)}.cd-first-lesson>.cosmic-bright-card{position:relative;z-index:1;overflow:hidden;border:1px solid rgba(210,226,255,.24)!important;border-radius:32px!important;background:linear-gradient(145deg,rgba(255,255,255,.14),rgba(105,95,202,.07))!important;box-shadow:0 32px 100px rgba(0,0,0,.48)!important}.cd-first-mascot{margin-bottom:-11px;filter:drop-shadow(0 18px 22px rgba(129,109,255,.28))}.cd-first-lesson h1{line-height:.96}.cd-first-points span{display:grid;gap:6px;justify-items:center;color:#b8c8e7;font-size:11px;letter-spacing:.1em}.cd-first-points b{display:grid;width:35px;height:35px;place-items:center;border-radius:50%;color:#0b1530;background:linear-gradient(135deg,#8ff1c7,#8edbff);box-shadow:0 0 20px rgba(143,241,199,.42);font-size:14px}.cd-first-lesson .cosmic-button{min-height:48px!important;border-radius:16px!important;font-weight:900!important}
`}</style></main>; }
