"use client";

import { useRouter } from "next/navigation";
import BrightCard from "../../../components/cosmic/BrightCard";
import CosmicButton from "../../../components/cosmic/CosmicButton";
import MascotMale from "../../../components/cosmic/MascotMale";
import MascotFemale from "../../../components/cosmic/MascotFemale";
import StarParticles from "../../../components/cosmic/StarParticles";
import { useCosmicUser } from "../../../components/cosmic/useCosmicUser";

export default function HomeIntroScreen({ onContinue }) { const router = useRouter(); const user = useCosmicUser(); const Mascot = user.cosmicGuide === "female" ? MascotFemale : MascotMale; const goal = Math.max(1, Number(user.dailyGoal) || 10); const progress = Math.min(100, Math.round(((Number(user.dailyXp) || 0) / goal) * 100)); return <main className="cosmic-dark cd-intro-screen cd-intro-home" style={{ position: "relative", display: "grid", placeItems: "center", padding: 22 }}><StarParticles color="#c9b5ff" /><span className="cd-intro-home-glow" aria-hidden="true" /><BrightCard style={{ position: "relative", width: "min(960px,100%)", display: "grid", gridTemplateColumns: "minmax(0,1fr) 220px", gap: 20, alignItems: "center" }}><div className="cd-home-copy"><p style={{ margin: 0, color: "#b9c9ef", fontWeight: 900 }}>WELCOME BACK</p><h1 style={{ margin: "8px 0", fontSize: "clamp(2.4rem,7vw,4.8rem)", letterSpacing: "-.06em" }}>Ready for your next ayah?</h1><div className="cd-home-stats" style={{ display: "flex", gap: 10, flexWrap: "wrap", margin: "18px 0" }}><span><b>{user.streak || 0}</b> day streak</span><span><b>{user.dailyXp || 0}</b> XP today</span><span><b>{goal}</b> XP goal</span></div><div className="cd-home-goal" role="progressbar" aria-label={`${progress}% of today's goal`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><i style={{ width: `${progress}%` }} /></div><div className="cd-home-actions" style={{ display: "flex", gap: 10, flexWrap: "wrap" }}><CosmicButton onClick={onContinue || (() => router.push("/cosmic/path"))}>Continue journey <span aria-hidden="true">→</span></CosmicButton><CosmicButton variant="outline" onClick={() => router.push("/cosmic/review")}>Review weak ayahs</CosmicButton><CosmicButton variant="outline" onClick={() => router.push("/cosmic/challenge")}>Daily challenge</CosmicButton><CosmicButton variant="dark" onClick={() => router.push("/cosmic/universe")}>Explore the Universe</CosmicButton></div></div><div className="cd-home-mascot"><Mascot energetic /></div></BrightCard><style jsx global>{`
  .cd-intro-home{min-height:calc(100svh - 64px);overflow:hidden;background:radial-gradient(circle at 76% 18%,rgba(120,94,250,.24),transparent 30%),radial-gradient(circle at 11% 83%,rgba(58,220,242,.13),transparent 35%),#060818!important}.cd-intro-home-glow{position:absolute;width:min(50vw,620px);aspect-ratio:1;right:-13%;top:-17%;border-radius:50%;background:radial-gradient(circle,rgba(164,117,255,.24),transparent 66%);filter:blur(4px)}.cd-intro-home>.cosmic-bright-card{z-index:1;overflow:hidden;padding:clamp(18px,3.4vw,36px)!important;border:1px solid rgba(213,226,255,.25)!important;border-radius:30px!important;background:linear-gradient(135deg,rgba(255,255,255,.14),rgba(89,92,178,.08))!important;box-shadow:0 30px 95px rgba(0,0,0,.46),inset 0 1px rgba(255,255,255,.18)!important}.cd-intro-home h1{line-height:.94;max-width:630px;font-size:clamp(2.05rem,6vw,4rem)!important}.cd-home-copy>p:first-child{font-size:11px;letter-spacing:.18em;color:#9ceccf!important}.cd-home-stats span{display:inline-flex;align-items:baseline;gap:5px;padding:8px 10px;border:1px solid rgba(194,218,255,.16);border-radius:13px;background:rgba(5,10,35,.28);color:#bdcee8;font-size:12px}.cd-home-stats b{color:#fff;font-size:16px}.cd-home-goal{position:relative;width:min(100%,460px);height:7px;margin:-5px 0 16px;overflow:hidden;border-radius:999px;background:rgba(191,213,255,.14)}.cd-home-goal i{position:absolute;inset:0 auto 0 0;border-radius:inherit;background:linear-gradient(90deg,#8ff1c7,#85ddff 62%,#c9a8ff);box-shadow:0 0 18px rgba(122,231,220,.7);transition:width .45s cubic-bezier(.16,1,.3,1)}.cd-home-actions .cosmic-button{min-height:41px!important;border-radius:14px!important;font-size:13px!important;font-weight:900!important}.cd-home-mascot{justify-self:center;transform:scale(.92);filter:drop-shadow(0 26px 22px rgba(82,84,255,.28))}@media(max-height:760px) and (min-width:701px){.cd-intro-home>.cosmic-bright-card{grid-template-columns:minmax(0,1fr) 160px!important;gap:12px!important}.cd-home-mascot{transform:scale(.72);margin-block:-34px}.cd-intro-home h1{font-size:clamp(2rem,5.2vw,3.25rem)!important}.cd-home-stats{margin:12px 0!important}.cd-home-actions .cosmic-button{min-height:38px!important;padding:8px 11px!important}}@media(max-width:700px){.cd-intro-home{align-items:start!important;padding:10px!important}.cd-intro-home>.cosmic-bright-card{grid-template-columns:1fr!important;text-align:center;max-height:calc(100svh - 84px);padding:16px!important}.cd-home-copy{display:grid;justify-items:center}.cd-home-actions{justify-content:center}.cd-home-actions .cosmic-button{flex:1 1 165px}.cd-home-mascot{order:-1;transform:scale(.68);margin-block:-50px -32px}.cd-home-stats{justify-content:center;margin:10px 0!important}.cd-intro-home h1{font-size:clamp(1.95rem,10vw,3rem)!important}.cd-home-goal{margin-bottom:12px}}
`}</style></main>; }
