"use client";

import BrightCard from "../../../components/cosmic/BrightCard";
import CosmicButton from "../../../components/cosmic/CosmicButton";
import MascotMale from "../../../components/cosmic/MascotMale";
import MascotFemale from "../../../components/cosmic/MascotFemale";
import StarParticles from "../../../components/cosmic/StarParticles";

export default function MascotSelection({ value, onChange, onContinue }) {
  return <main className="cosmic-dark cd-intro-screen cd-intro-choice" style={{ position: "relative", padding: "clamp(32px,8vw,86px) 20px" }}><StarParticles color="#d6b9ff" /><span className="cd-intro-orb cd-intro-orb--one" aria-hidden="true" /><section className="cd-intro-choice-inner" style={{ position: "relative", width: "min(820px,100%)", margin: "0 auto", textAlign: "center" }}><p className="cd-choice-kicker">STEP 1 OF 2</p><h1 style={{ fontSize: "clamp(2.4rem,7vw,4.6rem)", letterSpacing: "-.06em" }}>Choose your cosmic guide</h1><p style={{ color: "#c3d1ed" }}>A gentle companion for every ayah you learn.</p><div className="cd-intro-choice-grid" style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 18, margin: "32px 0" }}><BrightCard selected={value === "male"} onClick={() => onChange("male")}><MascotMale energetic={value === "male"} /><strong>Male cosmic Sheikh</strong><small>Calm, clear, and beside you.</small></BrightCard><BrightCard selected={value === "female"} onClick={() => onChange("female")}><MascotFemale energetic={value === "female"} /><strong>Female cosmic Sheikh</strong><small>Warm, steady, and encouraging.</small></BrightCard></div><CosmicButton disabled={!value} onClick={onContinue}>Continue <span aria-hidden="true">→</span></CosmicButton></section><style jsx global>{`
  .cd-intro-choice{min-height:calc(100svh - 64px);overflow:hidden;background:radial-gradient(circle at 50% 5%,rgba(97,78,220,.25),transparent 34%),radial-gradient(circle at 0 100%,rgba(64,234,236,.13),transparent 38%),#07091a!important}.cd-intro-choice-inner{z-index:1}.cd-choice-kicker{margin:0;color:#8ff1c7!important;font-size:11px;font-weight:950;letter-spacing:.2em}.cd-intro-choice h1{max-width:690px;margin:10px auto 8px;line-height:.96}.cd-intro-choice-grid>.cosmic-bright-card{min-height:292px;display:grid;align-content:center;justify-items:center;gap:8px;padding:25px!important;border:1px solid rgba(199,220,255,.2)!important;border-radius:26px!important;background:linear-gradient(160deg,rgba(255,255,255,.13),rgba(95,103,202,.08))!important;box-shadow:0 20px 48px rgba(0,0,0,.25)!important;transition:transform .23s cubic-bezier(.16,1,.3,1),border-color .23s ease,box-shadow .23s ease!important}.cd-intro-choice-grid>.cosmic-bright-card:hover{transform:translateY(-7px);border-color:rgba(148,242,211,.82)!important;box-shadow:0 24px 54px rgba(56,224,197,.16),inset 0 1px rgba(255,255,255,.24)!important}.cd-intro-choice-grid small{color:#aebfdc;font-size:12px}.cd-intro-choice .cosmic-button{border-radius:16px!important;min-height:48px!important;font-weight:900!important}.cd-intro-choice .cd-intro-orb{right:-17%;top:-25%;width:min(56vw,660px);background:radial-gradient(circle at 35% 35%,rgba(176,129,255,.3),transparent 64%)}@media(max-width:560px){.cd-intro-choice-grid{grid-template-columns:1fr!important}.cd-intro-choice-grid>.cosmic-bright-card{min-height:205px;padding:18px!important}.cd-intro-choice-grid .cosmic-mascot{transform:scale(.82);margin-block:-10px}.cd-intro-choice h1{font-size:clamp(2.2rem,12vw,3.5rem)!important}}
`}</style></main>;
}
