"use client";

import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getUser, updateUser } from "../../lib/user";
import { COSMIC_EMPTY_USER } from "./useCosmicUser";
import MascotMale from "./MascotMale";
import MascotFemale from "./MascotFemale";
import StreakFlame from "./StreakFlame";
import DailyGoalBar from "./DailyGoalBar";
import XPBubble from "./XPBubble";

const starStyle = (index) => ({ position: "absolute", left: `${(index * 37) % 96 + 2}%`, top: `${(index * 61) % 92 + 3}%`, width: index % 3 ? 3 : 5, height: index % 3 ? 3 : 5, borderRadius: "50%", background: index % 4 ? "#dff8ff" : "#d5a5ff", boxShadow: "0 0 10px currentColor" });

export default function IntroScreen() {
  const router = useRouter();
  const [user, setUser] = useState(COSMIC_EMPTY_USER);
  const [guide, setGuide] = useState("");
  useEffect(() => { const refresh = () => { const current = getUser(); setUser(current); setGuide(current.cosmicGuide || ""); }; refresh(); window.addEventListener("sheikhduo-user-changed", refresh); return () => window.removeEventListener("sheikhduo-user-changed", refresh); }, []);
  function choose(next) { setGuide(next); updateUser({ cosmicGuide: next }); setUser(getUser()); }
  const Mascot = guide === "female" ? MascotFemale : MascotMale;
  return <main style={{ position: "relative", minHeight: "100vh", overflow: "hidden", color: "#eefaff", background: "radial-gradient(circle at 80% 20%,#46287a 0,transparent 30%),radial-gradient(circle at 14% 78%,#0b5471 0,transparent 34%),linear-gradient(145deg,#050818,#0b123a 54%,#050713)" }}><div aria-hidden="true" style={{ position: "absolute", inset: 0, pointerEvents: "none" }}>{Array.from({ length: 58 }, (_, index) => <motion.i key={index} style={starStyle(index)} animate={{ opacity: [.25, 1, .25], y: [0, index % 2 ? -10 : 10, 0] }} transition={{ delay: index * .03, duration: 2.3 + index % 3, repeat: Infinity }} />)}</div><motion.section initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }} style={{ position: "relative", zIndex: 1, width: "min(1000px,calc(100% - 32px))", minHeight: "calc(100vh - 64px)", display: "grid", alignContent: "center", gridTemplateColumns: "minmax(0,1.2fr) minmax(240px,.8fr)", gap: 34, margin: "0 auto", padding: "50px 0" }}><div><p style={{ margin: 0, color: "#9fefff", fontWeight: 900, letterSpacing: ".15em", textTransform: "uppercase", fontSize: 12 }}>Quran Tarteel</p><h1 style={{ maxWidth: 670, margin: "12px 0", fontSize: "clamp(3rem,9vw,6.2rem)", lineHeight: .96, letterSpacing: "-.06em" }}>Welcome back, {user.username || "traveler"}.</h1><p style={{ maxWidth: 560, color: "#c0d2e9", fontSize: "clamp(1rem,2vw,1.2rem)", lineHeight: 1.65 }}>Your Qur'an journey has a universe. Build a gentle daily learning habit through worlds, ayahs, and thoughtful rewards.</p><div style={{ display: "flex", gap: 16, flexWrap: "wrap", margin: "26px 0" }}><div style={{ padding: "13px 16px", borderRadius: 15, background: "rgba(255,255,255,.08)", fontWeight: 900 }}>{user.xp || 0} XP</div><div style={{ padding: "13px 16px", borderRadius: 15, background: "rgba(255,255,255,.08)" }}><StreakFlame streak={user.streak || 0} /></div></div><DailyGoalBar user={user} />
      {!guide ? <div style={{ marginTop: 30, padding: 20, border: "1px solid rgba(169,233,255,.25)", borderRadius: 20, background: "rgba(7,15,48,.68)" }}><h2 style={{ marginTop: 0 }}>Choose your cosmic Sheikh guide</h2><div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}><button type="button" onClick={() => choose("male")} style={{ border: "1px solid #a8e9ff", borderRadius: 13, padding: "12px 16px", color: "#e9faff", background: "#17376e", cursor: "pointer", fontWeight: 900 }}>Male cosmic Sheikh</button><button type="button" onClick={() => choose("female")} style={{ border: "1px solid #f0b6ff", borderRadius: 13, padding: "12px 16px", color: "#fff0ff", background: "#5b236f", cursor: "pointer", fontWeight: 900 }}>Female cosmic Sheikh</button></div></div> : <div style={{ display: "flex", flexWrap: "wrap", gap: 12, marginTop: 30 }}><button type="button" onClick={() => router.push("/cosmic/path")} style={{ border: "none", borderRadius: 14, padding: "14px 20px", color: "#071528", background: "#9eeaff", cursor: "pointer", fontWeight: 900 }}>Continue</button><button type="button" onClick={() => router.push("/cosmic/review")} style={{ border: "1px solid rgba(255,255,255,.28)", borderRadius: 14, padding: "14px 20px", color: "#effaff", background: "transparent", cursor: "pointer", fontWeight: 900 }}>Review weak ayahs</button><button type="button" onClick={() => router.push("/cosmic/challenge")} style={{ border: "1px solid #ffdc7c", borderRadius: 14, padding: "14px 20px", color: "#fff4cf", background: "rgba(209,147,38,.18)", cursor: "pointer", fontWeight: 900 }}>Daily challenge</button></div>}</div><aside style={{ alignSelf: "center", padding: 22, border: "1px solid rgba(175,235,255,.18)", borderRadius: 30, background: "rgba(8,16,52,.48)", textAlign: "center", backdropFilter: "blur(9px)" }}><Mascot energetic={Boolean(guide)} /><p style={{ margin: 0, color: "#b8d1e8", lineHeight: 1.55 }}>{guide ? "Your guide is ready to travel with you." : "A calm companion for every lesson."}</p></aside></motion.section><XPBubble /></main>;
}
