"use client";

import { motion } from "framer-motion";
import QuestProgress from "./QuestProgress";
import QuestReward from "./QuestReward";

export default function QuestCard({ quest, onOpen }) {
  return <motion.article className="cosmic-v2-card" whileHover={{ y: -4, scale: 1.008 }} style={{ display: "grid", gap: 13, padding: 18, borderRadius: 20, border: `1px solid ${quest.claimed ? "rgba(255,219,126,.38)" : quest.complete ? "rgba(135,240,193,.42)" : "rgba(176,208,248,.16)"}`, background: quest.claimed ? "linear-gradient(135deg,rgba(165,112,39,.2),rgba(84,56,151,.14))" : "rgba(255,255,255,.045)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 14, alignItems: "flex-start" }}><div style={{ display: "flex", gap: 12, minWidth: 0 }}><span aria-hidden="true" style={{ width: 46, height: 46, display: "grid", placeItems: "center", flex: "0 0 auto", borderRadius: 15, background: quest.claimed ? "#b77c2d" : "rgba(118,214,255,.13)", boxShadow: quest.complete ? "0 0 16px rgba(124,238,197,.35)" : "none", fontSize: 24 }}>{quest.icon}</span><div><p style={{ margin: 0, color: "#ffdc8c", fontSize: 11, fontWeight: 900, letterSpacing: ".12em" }}>{quest.category.toUpperCase()}</p><h2 style={{ margin: "3px 0 5px", color: "#f2f8ff", fontSize: 19 }}>{quest.name}</h2><p style={{ margin: 0, color: "#b9cae4", lineHeight: 1.45, fontSize: 13 }}>{quest.description}</p></div></div><small style={{ color: quest.claimed ? "#ffe38f" : quest.complete ? "#a9f3ca" : "#9ab0d1", fontWeight: 900, whiteSpace: "nowrap" }}>{quest.claimed ? "Claimed" : quest.complete ? "Ready" : "In progress"}</small></div><QuestProgress value={quest.value} target={quest.target} complete={quest.complete} /><QuestReward xp={quest.xp} cosmetic={quest.cosmetic} claimed={quest.claimed} /><button type="button" onClick={() => onOpen(quest)} className={quest.complete && !quest.claimed ? "cosmic-button" : "cosmic-button cosmic-button--outline"}>{quest.complete && !quest.claimed ? "Claim reward" : "View quest"}</button></motion.article>;
}
