"use client";

import { useState } from "react";

export default function SocialProfilePreview({ friend, onClose }) {
  const [expanded, setExpanded] = useState(false);
  if (!friend) return null;
  return <section className="cosmic-bright-card" style={{ padding: 18, borderRadius: 20, display: "grid", gap: 13 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "start" }}><div style={{ display: "flex", gap: 11, alignItems: "center" }}><span aria-hidden="true" style={{ width: 52, height: 52, display: "grid", placeItems: "center", borderRadius: "50%", background: friend.color, fontSize: 24 }}>{friend.avatar}</span><div><p style={{ margin: 0, color: "#ffdc8a", fontSize: 11, fontWeight: 900 }}>TRAVELER PROFILE</p><h2 style={{ margin: "3px 0" }}>{friend.name}</h2></div></div><button type="button" onClick={onClose} style={{ border: 0, cursor: "pointer", color: "#c5d5eb", background: "transparent" }}>✕</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 8 }}>{[["XP", friend.xp], ["Streak", `${friend.streak} 🔥`], ["Mastery", `${friend.mastery}%`]].map(([label, value]) => <div key={label} style={{ padding: "10px 6px", borderRadius: 12, textAlign: "center", background: "rgba(255,255,255,.055)" }}><strong style={{ display: "block" }}>{value}</strong><small style={{ color: "#aebfda" }}>{label}</small></div>)}</div><p style={{ margin: 0, color: "#c1d1e8", fontSize: 13 }}>{friend.badge || "A calm explorer of the Qur'an cosmos."}</p>{expanded ? <div style={{ padding: 12, borderRadius: 13, color: "#c8d8ed", background: "rgba(113,145,255,.1)", fontSize: 13, lineHeight: 1.5 }}>Achievement highlight: {friend.badge || "Cosmic companion"}. This traveler&apos;s mastery ring is currently glowing at {friend.mastery}%.</div> : null}<button type="button" onClick={() => setExpanded((value) => !value)} className="cosmic-button cosmic-button--outline">{expanded ? "Close full profile" : "View full profile"}</button></section>;
}
